/**
 * Every external link, every piece of identity copy, once.
 * Components must not hard-code any of this.
 */

export const person = {
  name: 'Arihant Jain',
  /** The one line. Stated, not performed. */
  statement:
    'I build multi-agent AI systems, security tooling, and full-stack products.',
  school: 'Amity University Noida',
  degree: 'B.Tech Computer Science',
  span: '2024 — 2028',
  location: 'Noida, India',
  email: 'arihantjain4309@gmail.com',
} as const;

export const links = {
  github: 'https://github.com/arihantjaino7',
  linkedin: 'https://linkedin.com/in/arihant-jain43',
  x: 'https://x.com/arihantjaino7',
  get email() {
    return `mailto:${person.email}`;
  },
} as const;

export const nav = [
  { href: '/work', label: 'work' },
  { href: '/about', label: 'about' },
] as const;

export const meta = {
  defaultTitle: `${person.name} — software engineer`,
  titleTemplate: (t: string) => `${t} — ${person.name}`,
  description:
    'Arihant Jain builds multi-agent AI systems, security tooling, and full-stack products. CS undergrad at Amity University Noida.',
  locale: 'en_IN',
  twitterHandle: '@arihantjaino7',
} as const;

/** Chapter IV. The figures are the visual element — PLAN.md §2. */
export const achievements = [
  {
    figure: '1st',
    countTo: 1,
    event: 'Amity Ideathon',
    year: '2026',
    detail: 'AI / Digital Technologies & Smart Systems',
  },
  {
    figure: '12th',
    countTo: 12,
    event: 'OMNIKON National Hackathon',
    year: '2026',
    detail: 'of 3,000+ submissions nationwide',
  },
  {
    figure: 'top 6%',
    countTo: 6,
    event: 'Adobe Hackathon',
    year: '2026',
    detail: 'nationally',
  },
] as const;

/** Chapter III. Prose only — no icons, no cards. A set, so unnumbered. */
export const areas = [
  {
    title: 'Multi-agent systems',
    body: 'Concurrent agents that each own one narrow question, run together, and reconcile into a single answer. The hard part is never the agents — it is making the merged result deterministic enough to defend.',
  },
  {
    title: 'Backend and API design',
    body: 'FastAPI and Next.js route handlers over Postgres. I care about where a rule is enforced: a constraint that lives in application code is a suggestion, and I would rather spend a day moving it into the database.',
  },
  {
    title: 'Security tooling',
    body: 'Passive analysis over live attack traffic. Scanners that grade rather than alarm, fixes generated by deterministic code rather than a model, and every change previewed as a diff before anything is written.',
  },
  {
    title: 'Full-stack shipping',
    body: 'Typed end to end, tested with Vitest and Playwright, deployed on Cloudflare. Shipped means a real person used it and the thing held — not that the branch merged.',
  },
] as const;

/** /about — grouped by kind, never numbered, never percentage bars. */
export const skills = [
  { group: 'languages', items: ['Python', 'C++', 'Java', 'TypeScript', 'JavaScript', 'SQL'] },
  { group: 'frameworks', items: ['FastAPI', 'LangGraph', 'Next.js', 'React', 'Tailwind', 'Vite'] },
  { group: 'data', items: ['PostgreSQL (Supabase)', 'SQLite', 'Row-Level Security'] },
  { group: 'tooling', items: ['Git', 'Vitest', 'Playwright', 'Cloudflare Workers', 'Groq API'] },
] as const;
